### ISSUE TITLE
Wie kann ich den Vaterartikel in der CSV anzeigen lassen?

### ISSUE THREAD

**Issue by heikihei** [marmaladeDE/csvexporter#2]
im Configurationsbereich gibt es die Möglichkeit zu definieren ob der Vaterartikel dargestellt wird oder nicht:

Standardmäßig sieht die Zeile so aus:
'export_parents'                => 0,               // Should parents be shown in file !!!not availab

Ich habe es mit einer 1 oder mit true versucht, beides funktioniert nicht. Ich brauche aber dringend den übergeordneten Vaterartikel. Kann jemand helfen?

**Comment by jkrug** [comment]
Hi,
"!!!not abailable" meint, dass das feature angedacht ist, aber noch nicht umgesetzt. Gerne nehemen wir einen pull request auf!

Gruß Joscha
