### ISSUE TITLE
Attribute exportieren

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [marmaladeDE/csvexporter#4]
Hallo zusammen,

versuche mittels des "marmaladeDE/csvexporter" Attribute aus Oxid in eine CSV zu bringen.
Kann mir jemand einen kleinen Wink geben wie ich da vorgehen soll.

Danke!

**Comment by jkrug** [comment]
Hallo,

meine Bitte: Solche Fragen ins OXID Forum, damit die ganze Community helfen kann. Wir bieten als Agentur gerne professionellen Support an und - soweit es die Zeit zulässt - an zentraler Stelle im OXID Forum.

Gruß Joscha
